### ISSUE TITLE
Clean up legacy helper code

### ISSUE THREAD

**Issue by dereuromark** [dereuromark/cakephp-calendar#1]
and
- refactor into either widget or templates for table layout

also:
- provide a full responsive alternative using divs (instead of table)

Check if we can leverage http://yohan.giarel.li/CalendR/

**Comment by mferak** [comment]
Hi. Would a part of this be a possibility to translate the calendar? Thanks!

**Comment by dereuromark** [comment]
Most of it already is translated via __() right?
Please help out to further improve.

**Comment by mferak** [comment]
Well, parts of the code are like this:

`__(ucfirst($this->monthName($month)))`

Which seems like a "dirty" solution - for instance it won't get picked up by the i18n shell extract, as far as I understand. Furthermore, the month names are already defined for translation in cake (datetime widget), so it's sort of redundant having to translate the month names in two separate places.

**Comment by dereuromark** [comment]
You are right - Are you able to provide a PR here to leverage the cake ones if they are available?
Otherwise we need to find a more explicit way.

**Comment by mferak** [comment]
I would be glad to help, however, I only tried making a PR once so far (in CakeDC Users project), and it didn't really work out 😢. Seems like I don't know how to do it properly.

**Comment by dereuromark** [comment]
Give it another try. I am sure we can figure it out together.

**Comment by mferak** [comment]
OK, I'll give it a go tomorrow. Thanks!
