### ISSUE TITLE
A  sql schema for events 

### ISSUE THREAD

**Issue by dlr4spotloc** [dereuromark/cakephp-calendar#12]
Hi,
interesting (thank you by the way :)) 
 i think database sql is missing for this plugin ?

Regards
David

**Comment by dereuromark** [comment]
It also doesnt come with Model (Entity, Table) and Controller etc to keep it agnostic.
I didnt want to make assumptions on how a event table would look like as this differs very much between each use case.
So best to provide this on app level instead.

**Comment by dlr4spotloc** [comment]
yes, 
by digging a little i also noticed that and you're right.

Many thanks for this work.

Regards
David
