### ISSUE TITLE
Allow URL parameters to be passed in to `previous` and `next` links

### ISSUE THREAD

**Issue by curtisgibby** [dereuromark/cakephp-calendar#16]
So that filtering variables can be passed from the current month view (e.g. January 2021 having a URI string like `events/calendar?filter_key=123`) to the `previous`link (`events/calendar/2020/12?filter_key=123`) and the `next` link (`events/calendar/2021/02?filter_key=123`)

**Comment by dereuromark** [comment]
Can you make a PR of what you mean?

**Comment by curtisgibby** [comment]
Fixed in #17;
