### ISSUE TITLE
Months in year/Days in month listing helper

### ISSUE THREAD

**Issue by JeanValJeann** [dereuromark/cakephp-calendar#21]
Hi there,

I'm currently implementing this one Calendar Plugin in my project and some questions came up in my mind.
Those questions came up about the Helper and how to go further with its.
The Helper provides great methods and I was thinking about two other ones that'd help to render more fonctionnalities in our differents own project views.

- What about a method that'd render a month's list link of the current years provided in URL ?
`$this->Calendar->monthsList($year)`

- What about a method that'd render a day's list link of all days including in the current  month provided in URL ?
`$this->Calendar->daysList($month)`

The render() method into the Helper is great especially for an Admin page.
My suggestions come inside an enhancement to handle more fonctionnalities in frontEnd.

Sorry, I haven't been able to find how to labelized this issue which is not one.
My message is about an enhancement :)

**Comment by dereuromark** [comment]
@JeanValJeann Are you interested in following up on this?

**Comment by JeanValJeann** [comment]
Sorry dereuromark to make too munch time for giving you back a reply.
I've been take apart of programation for several months, I'm now okay for it.
Before starting to work on it. Is there anyone in here to suggest some other enhancement ?

**Comment by dereuromark** [comment]
Go for it.

**Comment by dereuromark** [comment]
Still interested in helping out?

**Comment by dereuromark** [comment]
ping @JeanValJeann
