### ISSUE TITLE
Call to a member function set() on null on ```$this->Controller->set('_calendar', $viewVars);```

### ISSUE THREAD

**Issue by hiryu85** [dereuromark/cakephp-calendar#23]
Hi,
Latests version of this plugin raise this exception:

```php
// exception: Call to a member function set() on null
// file: vendor\dereuromark\cakephp-calendar\src\Controller\Component\CalendarComponent.php
// line: 109
$this->Controller->set('_calendar', $viewVars);
```

Controller property is null, CalendarComponent::startup not seems called.

**Comment by dereuromark** [comment]
Are you able to make a PR that fixes things?

**Comment by hiryu85** [comment]
> Are you able to make a PR that fixes things?

Yeah! I can try.

```php
    public function calendar($year = null, $month = null)
    {
        $this->loadComponent('Calendar.Calendar', [
            'field'    => 'created',
            'endField' => 'created',
            'scope'    => ['deleted' => false],
        ]);
       // ......
```

The problem: if i load component into my action CalendarComponent::startup not called. Into my Controller's beforeFilter is called.
For me, this component can replace

```php
$this->Controller->set('_calendar', $viewVars);
```


with 

```php
$this->getController()->set('_calendar', $viewVars);
```

in your opinion is it the correct solution?

**Comment by hiryu85** [comment]
https://github.com/hiryu85/cakephp-calendar/pull/1
