### ISSUE TITLE
$this->Calendar->addRowFromTo throws Memory Exception

### ISSUE THREAD

**Issue by r0boto** [dereuromark/cakephp-calendar#6]
Hi, 

using the function addRowFromTois throwing the following exception

> Error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 20 bytes) 
> File /app/vendor/cakephp/chronos/src/Traits/ModifierTrait.php 
> Line: 456

Usage

```
foreach ($events as $event) {
                    $content = $this->Html->link($event->name, ['action' => 'view', $event->id]);
                    //$this->Calendar->addRow($event->begin, $content, ['class' => 'event event_type'.$event->events_categories_id]);
                    $this->Calendar->addRowFromTo($event->begin, $event->end, $content, []);
                }
```
**Note:**
$this->Calendar->addRow works fine without exception.

**Using the following version:**
"dereuromark/cakephp-calendar": "^0.3.0",

Is possible to use some hotfix solution for this?

**Comment by dereuromark** [comment]
Do you know what the cause is? What exactly happens here?
If you could provide a PR with the fix, that would be awesome. I didnt encounter this.

Would otherwise be nice to have a small example data set to reproduce.

**Comment by r0boto** [comment]
Seems to be caused passing $content into addRowFromTo, when I left the attribute as empty array.
`$this->Calendar->addRowFromTo($event->begin, $event->end, [], []);`
No Excpeption has been throwned. 
I checked that event end in dataset is not before event start.
Type of the column for event.start & event.begin is date time.

I tried to provide different passed content, but without the luck, It works only with empty array.

**Comment by dereuromark** [comment]
I would expect chronos to throw some exception.
Let me check in my app.

**Comment by dereuromark** [comment]
Please make sure you use the right documented types.
For me this is not reproducible with

    $this->Calendar->addRowFromTo($event['beginning'], $event['end'], $content, ['class' => 'event']);

and $content being the documented string (or empty one). Empty array here is not allowed but I would not see how this would create the issue you are talking about.

**Comment by hassifmohd** [comment]
i know how to reproduce
if your data is from database example events.event_start_date

then events.event_start_date will be FrozenDateTime()
because of that `$from->addDay();` the date will not increase
thus we are getting infinite while loop

to solve

at [dereuromark/cakephp-calendar/src/View/Helper/CalendarHelper.php](https://github.com/dereuromark/cakephp-calendar/blob/master/src/View/Helper/CalendarHelper.php#L88)
function `addRowFromTo(...)`
```
$from = new Time($from);
// $from = clone $from; //remove this
```

**Comment by dereuromark** [comment]
Ah thanks for the clarification
But you must clone it if it is not of type Frozen to ensure it doesnt change the incoming object for side effects.
We might better fix it differently, by always assigning the changed value back, as true immutability would suggest anyway.

**Comment by dereuromark** [comment]
@hassifmohd Can you please check if my PR fixes this?

**Comment by hassifmohd** [comment]
@dereuromark 

> @hassifmohd Can you please check if my PR fixes this?

yes it works
