### ISSUE TITLE
Argument 1 passed to Calendar\View\Helper\CalendarHelper::addRow()

### ISSUE THREAD

**Issue by jeromewalitzek** [dereuromark/cakephp-calendar#9]
Hi Mark,

i have done all what is written in you docs. but I always get the following error with cakephp 3.7

"Argument 1 passed to Calendar\View\Helper\CalendarHelper::addRow() must implement interface Cake\Chronos\ChronosInterface, null given, called in /var/www/calenderproject/src/Template/Events/index.ctp on line 72"

The Line 72 is the line with "$content = $this->.... from your docs code

```
    <?php
        foreach ($events as $event) {
            $content = $this->Html->link($event->title, ['action' => 'view', $event->id]);
            $this->Calendar->addRow($event->date, $content, ['class' => 'event']);
        }

        echo $this->Calendar->render();
    ?>

    <?php if (!$this->Calendar->isCurrentMonth()) { ?>
        <?php echo $this->Html->link(__('Jump to the current month') . '...', ['action' => 'index'])?>
    <?php } ?>
```
Any ideas ?

Thanks for help

**Comment by dereuromark** [comment]
if you have no date (NULL), then please do not add a row here.
Check for it first (!== null).
